title: Global Peruvian Student Network (GPSN)
#logo
description: Connecting Peruvian talent across academic borders. Our network facilitates collaboration between Peruvian students at prestigious universities worldwide, promoting professional and academic development.
#show_downloads: true
theme: jekyll-theme-minimal
